### ISSUE TITLE
配置项可以由PHP传参数么？

### ISSUE THREAD

**Issue by littlehz** [liexusong/atom#5]
多个数据中心，多个server。要是每个php.ini都配置成不一样的话，感觉不太好。个人觉得通过PHP读取env环境变量，传参好些。

ukey.datacenter = integer
ukey.worker = integer
ukey.twepoch = uint64

**Comment by liexusong** [comment]
不行的，因为扩展初始化要用到这些配置，而初始化会比php代码先执行
