### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by chunhei2008** [liexusong/atom#6]
make 的时候出错，centos 64bit php版本 5.3.3   5.6.3都是一样
In file included from /home/wangyi/ukey-master/ukey.c:33:
/home/wangyi/ukey-master/php_ukey.h:75: error: conflicting types for ‘__uint64_t’
/usr/include/bits/types.h:45: note: previous declaration of ‘__uint64_t’ was here
/home/wangyi/ukey-master/ukey.c: In function ‘ukey_startup’:
/home/wangyi/ukey-master/ukey.c:136: warning: assignment from incompatible pointer type
/home/wangyi/ukey-master/ukey.c:137: warning: assignment from incompatible pointer type
/home/wangyi/ukey-master/ukey.c:147: warning: assignment from incompatible pointer type
/home/wangyi/ukey-master/ukey.c: In function ‘exit_cb’:
/home/wangyi/ukey-master/ukey.c:193: warning: comparison between pointer and integer
make: **\* [ukey.lo] Error 1

**Comment by rainingmaster** [comment]
我也遇到这个问题了，请问怎么解决

**Comment by kaijie713** [comment]
我晕，我也是这问题，怎么回事啊

**Comment by kaijie713** [comment]
64位ubuntu 12.04 
PHP Version 5.3.10-1ubuntu3.18
Apache/2.2.22 (Ubuntu)

**Comment by kaijie713** [comment]
/bin/bash /home/sunchen/下载/ukey-master/libtool --mode=compile cc  -I. -I/home/sunchen/下载/ukey-master -DPHP_ATOM_INC -I/home/sunchen/下载/ukey-master/include -I/home/sunchen/下载/ukey-master/main -I/home/sunchen/下载/ukey-master -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/sunchen/下载/ukey-master/ukey.c -o ukey.lo 
libtool: compile:  cc -I. -I/home/sunchen/下载/ukey-master -DPHP_ATOM_INC -I/home/sunchen/下载/ukey-master/include -I/home/sunchen/下载/ukey-master/main -I/home/sunchen/下载/ukey-master -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/sunchen/下载/ukey-master/ukey.c  -fPIC -DPIC -o .libs/ukey.o
In file included from /home/sunchen/下载/ukey-master/ukey.c:33:0:
/home/sunchen/下载/ukey-master/php_ukey.h:75:28: error: conflicting types for '__uint64_t'
/usr/include/x86_64-linux-gnu/bits/types.h:45:27: note: previous declaration of '__uint64_t' was here
/home/sunchen/下载/ukey-master/ukey.c: In function 'ukey_startup':
/home/sunchen/下载/ukey-master/ukey.c:136:14: warning: assignment from incompatible pointer type [enabled by default]
/home/sunchen/下载/ukey-master/ukey.c:137:17: warning: assignment from incompatible pointer type [enabled by default]
/home/sunchen/下载/ukey-master/ukey.c:147:17: warning: assignment from incompatible pointer type [enabled by default]
/home/sunchen/下载/ukey-master/ukey.c: In function 'exit_cb':
/home/sunchen/下载/ukey-master/ukey.c:193:14: warning: comparison between pointer and integer [enabled by default]
make: *** [ukey.lo] 错误 1

**Comment by leirenzhichui** [comment]
进入php_ukey.h

找到typedef unsigned long long __uint64_t; 这句代码，

改成typedef unsigned long __uint64_t; 

再进行make就可以了
